from .common import *

PUBLIC_REGISTER_ENABLED = False
DEBUG = False
TEMPLATE_DEBUG = False

SECRET_KEY = '$TAIGA_SECRET'

MEDIA_URL = "$TAIGA_SCHEME://$TAIGA_HOST$TAIGA_PORT/media/"
STATIC_URL = "$TAIGA_SCHEME://$TAIGA_HOST$TAIGA_PORT/static/"
ADMIN_MEDIA_PREFIX = "$TAIGA_SCHEME://$TAIGA_HOST$TAIGA_PORT/static/admin/"
SITES["api"]["scheme"] = "$TAIGA_SCHEME"
SITES["api"]["domain"] = "$TAIGA_HOST"
SITES["front"]["scheme"] = "$TAIGA_SCHEME"
SITES["front"]["domain"] = "$TAIGA_HOST"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "$POSTGRES_DB",
        "HOST": "$POSTGRES_HOST",
        "USER": "$POSTGRES_USER",
        "PASSWORD": "$POSTGRES_PASSWORD"
    }
}

DEFAULT_FROM_EMAIL = "$DEFAULT_FROM_EMAIL"
CHANGE_NOTIFICATIONS_MIN_INTERVAL = $CHANGE_NOTIFICATIONS_MIN_INTERVAL #seconds
EMAIL_BACKEND = '$EMAIL_BACKEND'
EMAIL_USE_TLS = $EMAIL_USE_TLS
EMAIL_USE_SSL = $EMAIL_USE_SSL # You cannot use both (TLS and SSL) at the same time!
EMAIL_HOST = '$EMAIL_HOST'
EMAIL_PORT = $EMAIL_PORT
EMAIL_HOST_USER = '$EMAIL_HOST_USER'
EMAIL_HOST_PASSWORD = '$EMAIL_HOST_PASSWORD'

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://$RABBIT_USER:$RABBIT_PASSWORD@$RABBIT_HOST:$RABBIT_PORT/$RABBIT_VHOST"}

CELERY_ENABLED = True
